# Generated by Django 3.2.9 on 2021-11-06 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField()),
                ('age', models.IntegerField()),
                ('proffession', models.CharField(default='', max_length=100)),
                ('sex', models.CharField(default='', max_length=10)),
                ('height', models.CharField(default='', max_length=20)),
                ('religion', models.CharField(default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
