# Generated by Django 3.2.9 on 2021-12-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20211210_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinfo',
            old_name='other_info',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='proffession',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='height',
            field=models.IntegerField(),
        ),
    ]
