# Generated by Django 3.2.9 on 2021-12-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20211211_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinfo',
            old_name='proffession',
            new_name='profession',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
