# Generated by Django 3.2.9 on 2021-12-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_profileinfo_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='interests',
            fields=[
                ('who', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Accounts.userprofile')),
                ('toWhom', models.IntegerField()),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
