# Generated by Django 3.2.9 on 2021-12-22 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_alter_interests_who'),
    ]

    operations = [
        migrations.CreateModel(
            name='matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toWhom', models.IntegerField()),
                ('name', models.CharField(default='', max_length=200)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='interests',
        ),
    ]
