# Generated by Django 3.2.9 on 2021-12-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_auto_20211222_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matching',
            name='name',
        ),
        migrations.AlterField(
            model_name='matching',
            name='who',
            field=models.IntegerField(),
        ),
    ]
