# Generated by Django 3.2.9 on 2021-12-22 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_auto_20211223_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
