# Generated by Django 3.2.9 on 2021-12-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_alter_matching_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='who',
            field=models.IntegerField(),
        ),
    ]
